package com.sinovdeath.PetsOwnerSimulator.helpers.generators.animals;

import com.sinovdeath.PetsOwnerSimulator.constants.Constants;
import com.sinovdeath.PetsOwnerSimulator.entities.pet.Animal;
import com.sinovdeath.PetsOwnerSimulator.entities.pet.Animation;
import com.sinovdeath.PetsOwnerSimulator.entities.pet.Cat;
import com.sinovdeath.PetsOwnerSimulator.entities.pet.Image;
import com.sinovdeath.PetsOwnerSimulator.entities.stats.MoodStats;
import com.sinovdeath.PetsOwnerSimulator.entities.stats.Stats;
import com.sinovdeath.PetsOwnerSimulator.entities.stats.StatsIncreasing;
import com.sinovdeath.PetsOwnerSimulator.enums.AnimalType;
import com.sinovdeath.PetsOwnerSimulator.enums.UriType;

import java.util.ArrayList;
import java.util.List;

public class CatsGenerator {
    public static List<Animal> generateCats() {
        List<Animal> cats = new ArrayList<>();
        String catLick = String.format("%s/%s%s", Constants.ASSETS_TONGUE_FOLDER, "lick", Constants.ANIMATION_EXT);
        Animation lickAnimation = new Animation(catLick);

        Animal coffee = new Cat();
        coffee.setId("cat-1");
        coffee.setName("Coffee");
        String coffeeName = coffee.getName().toLowerCase();
        String coffeeRegularUri = String.format("%s/%s/%s%s", Constants.ASSETS_CATS_FOLDER, coffeeName, coffeeName, Constants.IMAGE_EXT);
        String coffeeSad = String.format("%s/%s/%s%s", Constants.ASSETS_CATS_FOLDER, coffeeName, UriType.SAD.getUriValue(), Constants.IMAGE_EXT);
        String coffeeSleeping = String.format("%s/%s/%s%s", Constants.ASSETS_CATS_FOLDER, coffeeName, UriType.SLEEPING.getUriValue(), Constants.IMAGE_EXT);
        String coffeeDead = String.format("%s/%s%s", Constants.ASSETS_DEAD_FOLDER, UriType.SHORT_HAIR.getUriValue(), Constants.IMAGE_EXT);
        Image coffeeImage = new Image(coffeeRegularUri, coffeeSad, coffeeSleeping, coffeeDead);
        coffee.setAnimation(lickAnimation);
        coffee.setImg(coffeeImage);
        Stats coffeeMaxValues = new Stats(720, 720, 360, 60);
        coffee.setMaxValues(coffeeMaxValues);
        Stats coffeeStats = new Stats(coffeeMaxValues.getHealth(), coffeeMaxValues.getSatiety(), coffeeMaxValues.getMood(), coffeeMaxValues.getDigestion());
        coffee.setStats(coffeeStats);
        Stats coffeeStatsReducing = new Stats(1, 1, 1, 1);
        coffee.setStatsReducing(coffeeStatsReducing);
        MoodStats coffeeMoodStats = new MoodStats(10, 70, 10, 10, 70);
        StatsIncreasing coffeeStatsIncreasing = new StatsIncreasing(1,1,coffeeMoodStats,60);
        coffee.setStatsIncreasing(coffeeStatsIncreasing);
        coffee.setWasTaken(false);
        coffee.setBio("Coffee was born in a small café from a stray mother, who came there for food and shelter. Luckily owners of the café were very helpful. From the first days when  Coffee started to walk, it was clear that it’s a special kitty.  Coffee has a so known wobbly cat syndrome – lack of the movement coordination that results in always looking a bit “drunk”. The café owners spent a lot of time and money trying to help the kitten, but some things just cannot be fixed. But Coffee doesn’t care about this condition and doesn’t feel being different. It’s a happy playful cat, that requires just a little bit more attention than the others.");
        coffee.setType(AnimalType.CATS.getAnimalType());

        Animal donut = new Cat();
        donut.setId("cat-2");
        donut.setName("Donut");
        String donutName = donut.getName().toLowerCase();
        String donutRegularUri = String.format("%s/%s/%s%s", Constants.ASSETS_CATS_FOLDER, donutName, donutName, Constants.IMAGE_EXT);
        String donutSad = String.format("%s/%s/%s%s", Constants.ASSETS_CATS_FOLDER, donutName, UriType.SAD.getUriValue(), Constants.IMAGE_EXT);
        String donutSleeping = String.format("%s/%s/%s%s", Constants.ASSETS_CATS_FOLDER, donutName, UriType.SLEEPING.getUriValue(), Constants.IMAGE_EXT);
        String donutDead = String.format("%s/%s%s", Constants.ASSETS_DEAD_FOLDER, UriType.LONG_HAIR.getUriValue(), Constants.IMAGE_EXT);
        Image donutImage = new Image(donutRegularUri, donutSad, donutSleeping, donutDead);
        donut.setImg(donutImage);
        donut.setAnimation(lickAnimation);
        Stats donutMaxValues = new Stats(720, 720, 360, 60);
        donut.setMaxValues(donutMaxValues);
        Stats donutStats = new Stats(donutMaxValues.getHealth(), donutMaxValues.getSatiety(), donutMaxValues.getMood(), donutMaxValues.getDigestion());
        donut.setStats(donutStats);
        Stats donutStatsReducing = new Stats(1, 1, 1, 1);
        donut.setStatsReducing(donutStatsReducing);
        MoodStats donutMoodStats = new MoodStats(5, 35, 5, 5, 35);
        StatsIncreasing donutStatsIncreasing = new StatsIncreasing(1,1,donutMoodStats,30);
        donut.setStatsIncreasing(donutStatsIncreasing);
        donut.setWasTaken(false);
        donut.setBio("Donut was sold as a purebred sphynx without documents. It didn’t take long for the hair to grow and for the new owners to realize they wasted their money on something they didn’t want. For several days Donut was sitting under the balcony meowing to get family’s attention and couldn’t understand, why it is not possible to come back home from this scary place. After that someone, who saw the whole story, brough Donut to the animal shelter. Donut is selective about the food and has a behavior of a noble cat: never would throw an item from the table, never would steal any food from the human’s plate or dumpster, never would go into the dirty litter box.");
        donut.setType(AnimalType.CATS.getAnimalType());

        Animal lucius = new Cat();
        lucius.setId("cat-3");
        lucius.setName("Lucius");
        String luciusName = lucius.getName().toLowerCase();
        String luciusRegularUri = String.format("%s/%s/%s%s", Constants.ASSETS_CATS_FOLDER, luciusName, luciusName, Constants.IMAGE_EXT);
        String luciusSad = String.format("%s/%s/%s%s", Constants.ASSETS_CATS_FOLDER, luciusName, UriType.SAD.getUriValue(), Constants.IMAGE_EXT);
        String luciusSleeping = String.format("%s/%s/%s%s", Constants.ASSETS_CATS_FOLDER, luciusName, UriType.SLEEPING.getUriValue(), Constants.IMAGE_EXT);
        String luciusDead = String.format("%s/%s%s", Constants.ASSETS_DEAD_FOLDER, UriType.LONG_HAIR.getUriValue(), Constants.IMAGE_EXT);
        Image luciusImage = new Image(luciusRegularUri, luciusSad, luciusSleeping, luciusDead);
        lucius.setImg(luciusImage);
        lucius.setAnimation(lickAnimation);
        Stats luciusMaxValues = new Stats(720, 720, 360, 60);
        lucius.setMaxValues(luciusMaxValues);
        Stats luciusStats = new Stats(luciusMaxValues.getHealth(), luciusMaxValues.getSatiety(), luciusMaxValues.getMood(), luciusMaxValues.getDigestion());
        lucius.setStats(luciusStats);
        Stats luciusStatsReducing = new Stats(1, 1, 1, 1);
        lucius.setStatsReducing(luciusStatsReducing);
        MoodStats luciusMoodStats = new MoodStats(5, 35, 5, 5, 35);
        StatsIncreasing luciusStatsIncreasing = new StatsIncreasing(1,1,luciusMoodStats,30);
        lucius.setStatsIncreasing(luciusStatsIncreasing);
        lucius.setWasTaken(false);
        lucius.setBio("Lucius was caught by the volunteers for the sterilization. Normally, cats are brought back to the colony after they recover, but Lucius was absolutely deaf, and volunteers decided, it is risky to let such a kitten live in the streets. Being deaf is quite usual for the white cats with the blue eyes. Lucius doesn’t react to any human critics, can sleep even in the middle of the apocalypse and isn’t afraid of the vacuum cleaner. But somehow Lucius always knows when the canned cat food is opened.");
        lucius.setType(AnimalType.CATS.getAnimalType());

        Animal lucky = new Cat();
        lucky.setId("cat-4");
        lucky.setName("Lucky");
        String luckyName = lucky.getName().toLowerCase();
        String luckyRegularUri = String.format("%s/%s/%s%s", Constants.ASSETS_CATS_FOLDER, luckyName, luckyName, Constants.IMAGE_EXT);
        String luckySad = String.format("%s/%s/%s%s", Constants.ASSETS_CATS_FOLDER, luckyName, UriType.SAD.getUriValue(), Constants.IMAGE_EXT);
        String luckySleeping = String.format("%s/%s/%s%s", Constants.ASSETS_CATS_FOLDER, luckyName, UriType.SLEEPING.getUriValue(), Constants.IMAGE_EXT);
        String luckyDead = String.format("%s/%s%s", Constants.ASSETS_DEAD_FOLDER, UriType.SHORT_HAIR.getUriValue(), Constants.IMAGE_EXT);
        Image luckyImage = new Image(luckyRegularUri, luckySad, luckySleeping, luckyDead);
        lucky.setImg(luckyImage);
        lucky.setAnimation(lickAnimation);
        Stats luckyMaxValues = new Stats(720, 720, 360, 60);
        lucky.setMaxValues(luckyMaxValues);
        Stats luckyStats = new Stats(luckyMaxValues.getHealth(), luckyMaxValues.getSatiety(), luckyMaxValues.getMood(), luckyMaxValues.getDigestion());
        lucky.setStats(luckyStats);
        Stats luckyStatsReducing = new Stats(1, 1, 1, 1);
        lucky.setStatsReducing(luckyStatsReducing);
        MoodStats luckyMoodStats = new MoodStats(5, 35, 5, 5, 35);
        StatsIncreasing luckyStatsIncreasing = new StatsIncreasing(1,1,luckyMoodStats,30);
        lucky.setStatsIncreasing(luckyStatsIncreasing);
        lucky.setWasTaken(false);
        lucky.setBio("Lucky suddenly appeared in front of a car in the middle of a forest road. Far away from the civilization, completely alone. The driver, who found this ball of black fur, took a long walk around the place, but hasn’t noticed any house or a stray cat family. Just an opened backpack, that smelled of cat piss. Lucky was smelly too and covered in pine needles. The kitten hopped into the car without invitation, and sat in the front seat, periodically turning his head to check, if savior is still around. Lucky indeed.");
        lucky.setType(AnimalType.CATS.getAnimalType());

        Animal meesha = new Cat();
        meesha.setId("cat-5");
        meesha.setName("Meesha");
        String meeshaName = meesha.getName().toLowerCase();
        String meeshaRegularUri = String.format("%s/%s/%s%s", Constants.ASSETS_CATS_FOLDER, meeshaName, meeshaName, Constants.IMAGE_EXT);
        String meeshaSad = String.format("%s/%s/%s%s", Constants.ASSETS_CATS_FOLDER, meeshaName, UriType.SAD.getUriValue(), Constants.IMAGE_EXT);
        String meeshaSleeping = String.format("%s/%s/%s%s", Constants.ASSETS_CATS_FOLDER, meeshaName, UriType.SLEEPING.getUriValue(), Constants.IMAGE_EXT);
        String meeshaDead = String.format("%s/%s%s", Constants.ASSETS_DEAD_FOLDER, UriType.SHORT_HAIR.getUriValue(), Constants.IMAGE_EXT);
        Image meeshaImage = new Image(meeshaRegularUri, meeshaSad, meeshaSleeping, meeshaDead);
        meesha.setImg(meeshaImage);
        meesha.setAnimation(lickAnimation);
        Stats meeshaMaxValues = new Stats(720, 720, 360, 60);
        meesha.setMaxValues(meeshaMaxValues);
        Stats meeshaStats = new Stats(meeshaMaxValues.getHealth(), meeshaMaxValues.getSatiety(), meeshaMaxValues.getMood(), meeshaMaxValues.getDigestion());
        meesha.setStats(meeshaStats);
        Stats meeshaStatsReducing = new Stats(1, 1, 1, 1);
        meesha.setStatsReducing(meeshaStatsReducing);
        MoodStats meeshaMoodStats = new MoodStats(5, 35, 5, 5, 35);
        StatsIncreasing meeshaStatsIncreasing = new StatsIncreasing(1,1,meeshaMoodStats,30);
        meesha.setStatsIncreasing(meeshaStatsIncreasing);
        meesha.setWasTaken(false);
        meesha.setBio("Meesha was born in the summer house from a cat that children fed in their garden. Real stray kitten, who hissed at the humans and run away if someone tried to come closer. Nevertheless, Meesha knew every house, where people gladly shared their food with the homeless kittens, and always checked them all, living the best life. But happy summer ended with the autumn coming. People started to leave to the city. The village became empty. And it was scary. Much scarier than trying to befriend a human and Meesha came to the door of one of the last families still being here, meowing and asking to let in.");
        meesha.setType(AnimalType.CATS.getAnimalType());

        Animal muffin = new Cat();
        muffin.setId("cat-6");
        muffin.setName("Muffin");
        String muffinName = muffin.getName().toLowerCase();
        String muffinRegularUri = String.format("%s/%s/%s%s", Constants.ASSETS_CATS_FOLDER, muffinName, muffinName, Constants.IMAGE_EXT);
        String muffinSad = String.format("%s/%s/%s%s", Constants.ASSETS_CATS_FOLDER, muffinName, UriType.SAD.getUriValue(), Constants.IMAGE_EXT);
        String muffinSleeping = String.format("%s/%s/%s%s", Constants.ASSETS_CATS_FOLDER, muffinName, UriType.SLEEPING.getUriValue(), Constants.IMAGE_EXT);
        String muffinDead = String.format("%s/%s%s", Constants.ASSETS_DEAD_FOLDER, UriType.SHORT_HAIR.getUriValue(), Constants.IMAGE_EXT);
        Image muffinImage = new Image(muffinRegularUri, muffinSad, muffinSleeping, muffinDead);
        muffin.setImg(muffinImage);
        muffin.setAnimation(lickAnimation);
        Stats muffinMaxValues = new Stats(720, 720, 360, 60);
        muffin.setMaxValues(muffinMaxValues);
        Stats muffinStats = new Stats(muffinMaxValues.getHealth(), muffinMaxValues.getSatiety(), muffinMaxValues.getMood(), muffinMaxValues.getDigestion());
        muffin.setStats(muffinStats);
        Stats muffinStatsReducing = new Stats(1, 1, 1, 1);
        muffin.setStatsReducing(muffinStatsReducing);
        MoodStats muffinMoodStats = new MoodStats(5, 35, 5, 5, 35);
        StatsIncreasing muffinStatsIncreasing = new StatsIncreasing(1,1,muffinMoodStats,30);
        muffin.setStatsIncreasing(muffinStatsIncreasing);
        muffin.setWasTaken(false);
        muffin.setBio("Owners refused to neuter their cat, as, according to them, it is not natural and is also bad for her health, so she periodically gives birth. After that the owners have drown the kittens. This time mother found a good place to hide her only child, so the little one was only found after its’ eyes opened. Kitten was packed into a box and thrown into the nearest shelter’s territory. Shelter workers called the kitten Muffin.");
        muffin.setType(AnimalType.CATS.getAnimalType());

        Animal owl = new Cat();
        owl.setId("cat-7");
        owl.setName("Owl");
        String owlName = owl.getName().toLowerCase();
        String owlRegularUri = String.format("%s/%s/%s%s", Constants.ASSETS_CATS_FOLDER, owlName, owlName, Constants.IMAGE_EXT);
        String owlSad = String.format("%s/%s/%s%s", Constants.ASSETS_CATS_FOLDER, owlName, UriType.SAD.getUriValue(), Constants.IMAGE_EXT);
        String owlSleeping = String.format("%s/%s/%s%s", Constants.ASSETS_CATS_FOLDER, owlName, UriType.SLEEPING.getUriValue(), Constants.IMAGE_EXT);
        String owlDead = String.format("%s/%s%s", Constants.ASSETS_DEAD_FOLDER, UriType.FOLDED_EARS.getUriValue(), Constants.IMAGE_EXT);
        Image owlImage = new Image(owlRegularUri, owlSad, owlSleeping, owlDead);
        owl.setImg(owlImage);
        owl.setAnimation(lickAnimation);
        Stats owlMaxValues = new Stats(720, 720, 360, 60);
        owl.setMaxValues(owlMaxValues);
        Stats owlStats = new Stats(owlMaxValues.getHealth(), owlMaxValues.getSatiety(), owlMaxValues.getMood(), owlMaxValues.getDigestion());
        owl.setStats(owlStats);
        Stats owlStatsReducing = new Stats(1, 1, 1, 1);
        owl.setStatsReducing(owlStatsReducing);
        MoodStats owlMoodStats = new MoodStats(5, 35, 5, 5, 35);
        StatsIncreasing owlStatsIncreasing = new StatsIncreasing(1,1,owlMoodStats,30);
        owl.setStatsIncreasing(owlStatsIncreasing);
        owl.setWasTaken(false);
        owl.setBio("Owl is a purebred Scottish fold – a beautiful silver chinchilla with turquoise eyes and small ears. Almost whole life Owl spent in a dirty rusted cage in a kitten mill, producing dozens of offsprings. Fortunately, this place was found by the volunteers, who called the police and all the cats were taken to the vet and into a better shelter. Owl has weak paws with illegally removed nails, some chronic stomach disease and is not used to being a pet. Therefore, most of the time Owls spends lying on the windowsill looking at the sky, trees and birds. And sometimes even allows humans to stand nearby.");
        owl.setType(AnimalType.CATS.getAnimalType());

        Animal picasso = new Cat();
        picasso.setId("cat-8");
        picasso.setName("Picasso");
        String picassoName = picasso.getName().toLowerCase();
        String picassoRegularUri = String.format("%s/%s/%s%s", Constants.ASSETS_CATS_FOLDER, picassoName, picassoName, Constants.IMAGE_EXT);
        String picassoSad = String.format("%s/%s/%s%s", Constants.ASSETS_CATS_FOLDER, picassoName, UriType.SAD.getUriValue(), Constants.IMAGE_EXT);
        String picassoSleeping = String.format("%s/%s/%s%s", Constants.ASSETS_CATS_FOLDER, picassoName, UriType.SLEEPING.getUriValue(), Constants.IMAGE_EXT);
        String picassoDead = String.format("%s/%s%s", Constants.ASSETS_DEAD_FOLDER, UriType.SHORT_HAIR.getUriValue(), Constants.IMAGE_EXT);
        Image picassoImage = new Image(picassoRegularUri, picassoSad, picassoSleeping, picassoDead);
        picasso.setImg(picassoImage);
        picasso.setAnimation(lickAnimation);
        Stats picassoMaxValues = new Stats(720, 720, 360, 60);
        picasso.setMaxValues(picassoMaxValues);
        Stats picassoStats = new Stats(picassoMaxValues.getHealth(), picassoMaxValues.getSatiety(), picassoMaxValues.getMood(), picassoMaxValues.getDigestion());
        picasso.setStats(picassoStats);
        Stats picassoStatsReducing = new Stats(1, 1, 1, 1);
        picasso.setStatsReducing(picassoStatsReducing);
        MoodStats picassoMoodStats = new MoodStats(5, 35, 5, 5, 35);
        StatsIncreasing picassoStatsIncreasing = new StatsIncreasing(1,1,picassoMoodStats,30);
        picasso.setStatsIncreasing(picassoStatsIncreasing);
        picasso.setWasTaken(false);
        picasso.setBio("For many years Picasso used to be the companion of the old lady. Quite home without any children or other animals, where Picasso spent the days sleeping, looking through the window and purring to the bellowed human. And always getting the most delicious pieces of food right from the table. Unfortunately, sometimes owners pass away earlier than their pets. Right now, Picasso is stressed and confused. Not old yet but losing the “cuteness contest” to the kittens and having troubles to adapt to the new home quickly.");
        picasso.setType(AnimalType.CATS.getAnimalType());

        Animal qwerty = new Cat();
        qwerty.setId("cat-9");
        qwerty.setName("Qwerty");
        String qwertyName = qwerty.getName().toLowerCase();
        String qwertyRegularUri = String.format("%s/%s/%s%s", Constants.ASSETS_CATS_FOLDER, qwertyName, qwertyName, Constants.IMAGE_EXT);
        String qwertySad = String.format("%s/%s/%s%s", Constants.ASSETS_CATS_FOLDER, qwertyName, UriType.SAD.getUriValue(), Constants.IMAGE_EXT);
        String qwertySleeping = String.format("%s/%s/%s%s", Constants.ASSETS_CATS_FOLDER, qwertyName, UriType.SLEEPING.getUriValue(), Constants.IMAGE_EXT);
        String qwertyDead = String.format("%s/%s%s", Constants.ASSETS_DEAD_FOLDER, UriType.SHORT_HAIR.getUriValue(), Constants.IMAGE_EXT);
        Image qwertyImage = new Image(qwertyRegularUri, qwertySad, qwertySleeping, qwertyDead);
        qwerty.setImg(qwertyImage);
        qwerty.setAnimation(lickAnimation);
        Stats qwertyMaxValues = new Stats(720, 720, 360, 60);
        qwerty.setMaxValues(qwertyMaxValues);
        Stats qwertyStats = new Stats(qwertyMaxValues.getHealth(), qwertyMaxValues.getSatiety(), qwertyMaxValues.getMood(), qwertyMaxValues.getDigestion());
        qwerty.setStats(qwertyStats);
        Stats qwertyStatsReducing = new Stats(1, 1, 1, 1);
        qwerty.setStatsReducing(qwertyStatsReducing);
        MoodStats qwertyMoodStats = new MoodStats(5, 35, 5, 5, 35);
        StatsIncreasing qwertyStatsIncreasing = new StatsIncreasing(1,1,qwertyMoodStats,30);
        qwerty.setStatsIncreasing(qwertyStatsIncreasing);
        qwerty.setWasTaken(false);
        qwerty.setBio("Shelter employees sometimes say Qwerty is cursed. Qwerty was first adopted as a little kitten, but even a month hasn’t passed, until the owners came back and said they appeared to be allergic to cats. It wasn’t long until new home was found, but just a few weeks later Qwerty was returned to the shelter after breaking very expensive vase. Third family kept Qwerty for almost a year, but then they decided to move to another country and claimed it wouldn’t be possible to take the cat there. Qwerty doesn’t lose hope to get adopted forever, purring and offering to pet the belly to everybody, who is coming to the shelter.");
        qwerty.setType(AnimalType.CATS.getAnimalType());

        Animal sammy = new Cat();
        sammy.setId("cat-10");
        sammy.setName("Sammy");
        String sammyName = sammy.getName().toLowerCase();
        String sammyRegularUri = String.format("%s/%s/%s%s", Constants.ASSETS_CATS_FOLDER, sammyName, sammyName, Constants.IMAGE_EXT);
        String sammySad = String.format("%s/%s/%s%s", Constants.ASSETS_CATS_FOLDER, sammyName, UriType.SAD.getUriValue(), Constants.IMAGE_EXT);
        String sammySleeping = String.format("%s/%s/%s%s", Constants.ASSETS_CATS_FOLDER, sammyName, UriType.SLEEPING.getUriValue(), Constants.IMAGE_EXT);
        String sammyDead = String.format("%s/%s%s", Constants.ASSETS_DEAD_FOLDER, UriType.LONG_HAIR.getUriValue(), Constants.IMAGE_EXT);
        Image sammyImage = new Image(sammyRegularUri, sammySad, sammySleeping, sammyDead);
        sammy.setImg(sammyImage);
        sammy.setAnimation(lickAnimation);
        Stats sammyMaxValues = new Stats(720, 720, 360, 60);
        sammy.setMaxValues(sammyMaxValues);
        Stats sammyStats = new Stats(sammyMaxValues.getHealth(), sammyMaxValues.getSatiety(), sammyMaxValues.getMood(), sammyMaxValues.getDigestion());
        sammy.setStats(sammyStats);
        Stats sammyStatsReducing = new Stats(1, 1, 1, 1);
        sammy.setStatsReducing(sammyStatsReducing);
        MoodStats sammyMoodStats = new MoodStats(5, 35, 5, 5, 35);
        StatsIncreasing sammyStatsIncreasing = new StatsIncreasing(1,1,sammyMoodStats,30);
        sammy.setStatsIncreasing(sammyStatsIncreasing);
        sammy.setWasTaken(false);
        sammy.setBio("Some adult noticed a screaming and hissing box in the hands of a group of the children. One of them said, there is a kitten inside, and mom doesn’t allow to keep it because of the allergies. The adult asked, if it would be then possible to get the kitten. At first children declined the offer, claiming they were planning to build a house for the cat in the basement, but then agreed to exchange it for some money to buy ice-cream. “It’s not very friendly” – they warned handing the box to the new owner – “It scratches and bites”. At the adult’s home kitten was sitting under the couch for almost a week. Sammy is still afraid of loud noises and children, but otherwise it’s one of the loveliest cats in the universe.");
        sammy.setType(AnimalType.CATS.getAnimalType());

        Animal houdini = new Cat();
        houdini.setId("cat-11");
        houdini.setName("Houdini");
        String houdiniName = houdini.getName().toLowerCase();
        String houdiniRegularUri = String.format("%s/%s/%s%s", Constants.ASSETS_CATS_FOLDER, houdiniName, houdiniName, Constants.IMAGE_EXT);
        String houdiniSad = String.format("%s/%s/%s%s", Constants.ASSETS_CATS_FOLDER, houdiniName, UriType.SAD.getUriValue(), Constants.IMAGE_EXT);
        String houdiniSleeping = String.format("%s/%s/%s%s", Constants.ASSETS_CATS_FOLDER, houdiniName, UriType.SLEEPING.getUriValue(), Constants.IMAGE_EXT);
        String houdiniDead = String.format("%s/%s%s", Constants.ASSETS_DEAD_FOLDER, UriType.SHORT_HAIR.getUriValue(), Constants.IMAGE_EXT);
        Image houdiniImage = new Image(houdiniRegularUri, houdiniSad, houdiniSleeping, houdiniDead);
        houdini.setImg(houdiniImage);
        houdini.setAnimation(lickAnimation);
        Stats houdiniMaxValues = new Stats(720, 720, 360, 60);
        houdini.setMaxValues(houdiniMaxValues);
        Stats houdiniStats = new Stats(houdiniMaxValues.getHealth(), houdiniMaxValues.getSatiety(), houdiniMaxValues.getMood(), houdiniMaxValues.getDigestion());
        houdini.setStats(houdiniStats);
        Stats houdiniStatsReducing = new Stats(1, 1, 1, 1);
        houdini.setStatsReducing(houdiniStatsReducing);
        MoodStats houdiniMoodStats = new MoodStats(5, 35, 5, 5, 35);
        StatsIncreasing houdiniStatsIncreasing = new StatsIncreasing(1,1,houdiniMoodStats,30);
        houdini.setStatsIncreasing(houdiniStatsIncreasing);
        houdini.setWasTaken(false);
        houdini.setBio("Houdini is the sole survivor from the litter of kittens thrown into a dumpster in a closed box. Someone ensured, they wouldn’t make it out alive, securing the box with enormous amount of sticky tape. But Houdini was loud enough to be heard by a passing by human. Hungry, dehydrated and ill, Houdini was brought to the veterinary clinic. One eye lost the fight to the virus, the other one is left with impaired vision. But guess what – Houdini hasn’t lost faith in humanity. It’s a joyful and loving kitty ready to sleep on the lap of the human buddy forever. With just the small breaks for fun and food, of course.");
        houdini.setType(AnimalType.CATS.getAnimalType());

        cats.add(coffee);
        cats.add(donut);
        cats.add(lucius);
        cats.add(lucky);
        cats.add(meesha);
        cats.add(muffin);
        cats.add(owl);
        cats.add(picasso);
        cats.add(qwerty);
        cats.add(sammy);
        cats.add(houdini);

        return cats;
    }
}
